apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghitalazar/argocd_test.git
    targetRevision: main
    path: istio_charts/charts/gateway
    helm:
      parameters:
        - name: gateways.istio-ingressgateway.type
          value: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress

