apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
  namespace: default
data:
  index.html: |
    <html>
    <head><title>App 1</title></head>
    <body>
      <h1>This is App 1</h1>
    </body>
    </html>
