apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ghitalazar/argocd_test.git
    path: bookinfo/platform/kube
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

