apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-gateway
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/<your-user>/<your-repo>
    path: istio-gateway
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

