apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app2-vs
spec:
  hosts:
  - \"*\"
  gateways:
  - app2-gateway
  http:
  - route:
    - destination:
        host: app2
        port:
          number: 80
