apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
  namespace: default
data:
  index.html: |
    <html>
    <head><title>App 2</title></head>
    <body>
      <h1>This is App 2</h1>
    </body>
    </html>
